Milestone 3: Associations
jasonfelice/School-Library pull request #3
Opened 2022-07-21 13:50 UTC by jasonfelice

# School Library

### Classes
- [x] Created a `Classroom` class with `@label` instance variable
- [x] Created a `Book` class with `@title` & `@author` instance variables
- [x] Created a `Rental` class with `@date` instance variable

### Associations
- [x] Created the `has-many`/`belongs-to` relationship between `Classroom` and `Student`
- [x] Create the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`

2022-07-21 17:07 UTC, DeliceLydia requested changes
## Hi @jasonfelice,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! Highlights for your project:
- [ ] Awesome README
- [ ] No linter errors


## Required Changes ♻️
_Check the comments under the review._



### Cheers!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-07-21 17:07 UTC, DeliceLydia commented on classroom.rb
> +end
- [x] This class should have a method that serves as the 'has-many' side (a classroom has many students)
- [x] Make sure the `has-many` / `belongs-to` relationships between `Classroom` and `Student` are created: 
- [x] When adding a student to a classroom it also sets the classroom for the student: that means you should have `attr_reader :students`

2022-07-21 17:07 UTC, DeliceLydia commented on classroom.rb
> +end
- [x] Remember When setting the classroom for a student it also adds it to the classroom's students: that means you are missing the `Student` class that inherits `Person` it will have `attr_reader: classroom`
- [x] It will have a method that serves as the 'belongs-to' side (a student belongs to a classroom).

2022-07-21 17:07 UTC, DeliceLydia commented on book.rb
> +end
- [x] Remember you need to have `rentals` as `attr_accessor` as well and it should be initialized
- [x] Please add a method for adding `rentals` and remember the `book` itself should be sent as a parameter to create the new rental achieving the 'has-many' association. you can simply do:
```ruby
 def add_rental(person, date)
    Rental.new(date, self, person)
  end
```

2022-07-21 17:07 UTC, DeliceLydia commented on rental.rb
> +end
- [x] Please add `book` and `person` as `attr_accessor` too and they should be initialized

2022-07-21 17:07 UTC, DeliceLydia commented on rental.rb
> +end
- [ ] `The rental` should be added itself to the `@book` achieving the 'belongs-to' association you can add:
`book.rentals << self` after initializing `book` 
- [ ] `The rental` should be added itself to the `@person` the 'belongs-to' association, you can add:
`person.rentals << self` after initializing `person`

2022-07-21 17:07 UTC, DeliceLydia commented on rental.rb
> +end
- [ ] I am not able to find a `person` class but you should add `rentals` as `attr_accessor` then initialize it
- [ ] Add a method for adding `rentals` and remember `The person` itself should be sent as a parameter to create the new rental achieving the 'has-many' association you can do:
```ruby
 def add_rental(book, date)
    Rental.new(date, book, self)
  end
```

2022-07-22 05:46 UTC, jasonfelice commented
Thanks :)👍🏼

2022-07-22 05:51 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @jasonfelice       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-22 05:56 UTC, merged